name: 'Install Azure Workload Orchestration Extension'
description: 'Installs the Azure CLI Workload Orchestration extension'

inputs:
  extension-file:
    description: 'Path to the workload orchestration extension .whl file'
    required: false
    default: '.exts/workload_orchestration-1.1.8-py3-none-any.whl'

runs:
  using: composite
  steps:
    - name: Install Workload Orchestration Extension
      shell: bash
      run: |
        echo "INSTALLING CLI Extension workload-orchestration ..."
        echo
        az extension add --name workload-orchestration
        az workload-orchestration -h
        echo
