solution-templates:
  - solutionTemplateName: "testapp6-solution"
    baseconfig: "defaultbaseconfig.json"
    versions:
      - version: 0.3.0
        instanceName: "testapp6-inst-030"
        sites:
          - siteName: "graham"
            targets:
              - targetName: "ghm-li-1"
                override:
                  ErrorThreshold: 0301
                  TemperatureRangeMax: "03011"
