solution-templates:
  - solutionTemplateName: "testapp6-solution"
    baseconfig: "defaultbaseconfig.json"
    versions:
      - version: 0.3.0
        instanceName: "testapp6-inst-030"
        sites:
          - siteName: "frisco"
            targets:
              - targetName: "fsc-li-1"
                override:
                  ErrorThreshold: 0301
                  TemperatureRangeMax: "03011"

              - targetName: "fsc-li-2"
                override:
                  ErrorThreshold: 0302
                  TemperatureRangeMax: "03022"
          - siteName: "denver"
            targets:
              - targetName: "den-li-1"
                override:
                  ErrorThreshold: 600
                  TemperatureRangeMax: "60011"

