# Resusable sanity check workflow 
# create woready aks cluster
# setup and delete svcgrps, targets
# delete the aks cluster

name: wo-sanity (Reusable)

on:
  workflow_call:
    inputs:
      site:
        required: true
        type: string
      rg:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:

  wo-sanity:
    env:
      site: ${{ inputs.site }}
      rg: ${{ inputs.rg }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure setup
      id: azsetup
      uses: ./.github/actions/wo-azure-setup
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        azcliversion: "2.73.0"

    - name: Create connected aks cluster
      id: create-aks-conn-cluster
      uses: ./.github/actions/wo-create-aks-conn-cluster
      with:
        site: ${{ inputs.site }}
        rg: ${{ inputs.rg }}

    - name: Check for w-o readiness
      id: check-wo-ready
      uses: ./.github/actions/wo-check-woready-cluster
      with:
        site: ${{ inputs.site }}
        rg: ${{ inputs.rg }}

    - name: Create w-o ready cluster
      if: ${{ steps.check-wo-ready.outputs.woready == 'false' }}
      id: aksClsWo
      uses: ./.github/actions/wo-setup-woready-cluster
      with:
        site: ${{ inputs.sites }}
        rg: ${{ inputs.rg }}
        akscls: ${{ steps.check-wo-ready.outputs.akscls }}
        akscon: ${{ steps.check-wo-ready.outputs.akscon }}
        cusloc: ${{ steps.check-wo-ready.outputs.cusloc }}
        woextn: ${{ steps.check-wo-ready.outputs.woextn }}
        aiocrt: ${{ steps.check-wo-ready.outputs.aiocrt }}

    - name: Create service groups
      uses: ./.github/actions/wo-setup-svgrps
      with:
        site: ${{ inputs.site }}
        rg: ${{ inputs.rg }}

    - name: Create targets
      uses: ./.github/actions/wo-setup-targets
      with:
        site: ${{ inputs.sites }}
        rg: ${{ inputs.rg }}

    - name: Delete targets
      uses: ./.github/actions/wo-delete-targets
      with:
        site: ${{ inputs.sites }}
        rg: ${{ inputs.rg }}

    - name: check for target-svgrp associations
      if: ${{ steps.check-wo-ready.outputs.woready == 'true' }}
      id: check-svctar
      uses: ./.github/actions/wo-check-svc-tar
      with:
        site: ${{ inputs.sites }}
        rg: ${{ inputs.rg }}

    - name: Delete service groups if no assoc. targets found
      if: ${{ steps.check-svctar.outputs.svcfound == 'false' }}
      uses: ./.github/actions/wo-delete-svgrps
      with:
        site: ${{ inputs.site }}
        rg: ${{ inputs.rg }}

    - name: Delete aks connected cluster
      id: wo-delete-aks-conn-cluster
      uses: ./.github/actions/wo-delete-aks-conn-cluster
      with:
       site: ${{ github.event.inputs.sites }}
       rg: ${{ github.event.inputs.usesiterg }}
